### ISSUE TITLE
Date format applied on Big Sur (time and weekday works)

### ISSUE THREAD

**Issue by jpbochi** [tech-otaku/menu-bar-clock#1]
I have MacOS `11.0.1 (20B29)`.

I'm trying `./menu-bar-clock.sh "EEE d MMM HH:mm"` and the outcome is `Wed 18. 11. 13:22`.

The script does update the time format (i.e. the `HH:mm` part). The `EEE` part also works.

**Comment by tech-otaku** [comment]
That's the same format I use. In System Preferences > Language & Region the Region is set to `United Kingdom` and the menu bar clock displays `Wed 18 Nov 12:52`. If I set the region to `France` it displays `Wed 18 Nov at 12:52` and `Germany` `Wed 18. Nov 12:52`. I suspect it has something to do with your Region setting.

EDIT: Setting the Region to `Czechia` displays the date as `Wed 18.11. 12:52`
