### ISSUE TITLE
Monterey 16.6.2

### ISSUE THREAD

**Issue by prestigious-fig** [tech-otaku/menu-bar-clock#11]
Hello. I just updated from Big Sur to Monterey and lost the 'Sat 21 Jan 20:11' format ["EEE d MMM HH:mm"]. I've run the menu-bar-clock script with and without [killall SystemUIServer], restarting the computer each time. The text of the file _com.apple.menuextra.clock_ is gibberish, though. I pulled out the native file and replaced it with @kgorskii's text just to see, but that didn't work either. Do I need to do something to kill _com.apple.controlcenter.plist_? Or is it a loss altogether because I am set in the US region with US English?
Thanks!
![Screen Shot 2023-01-21 at 18 10 47](https://user-images.githubusercontent.com/123282409/213899421-de40efef-ddce-4858-ad2f-33549af913f9.jpg)

![Screen Shot 2023-01-21 at 20 15 25](https://user-images.githubusercontent.com/123282409/213899424-ebfd3792-81ce-434e-ad07-681988a2f3b5.jpg)
![Screen Shot 2023-01-21 at 20 15 34](https://user-images.githubusercontent.com/123282409/213899432-126cb290-f66f-469e-9516-70f07a3b1aa5.jpg)
![Screen Shot 2023-01-21 at 20 22 28](https://user-images.githubusercontent.com/123282409/213899434-075f764e-1026-4ba7-bda6-a337b7bf45fa.jpg)

![Screen Shot 2023-01-21 at 20 36 10](https://user-images.githubusercontent.com/123282409/213899564-5815c733-157e-4be6-9cc9-2dc6d325b615.jpg)

**Comment by tech-otaku** [comment]
@prestigious-fig 

> I just updated from Big Sur to Monterey and lost the 'Sat 21 Jan 20:11' format ["EEE d MMM HH:mm"].

Could you tell me what date format you're seeing. Are you referring to the `21 Jan` being `Jan 21`? Your screenshots suggest the format is correct for your region.

For me, on Monterey 12.6.2 with the following settings the date is displayed as expected:

| Region         | Preferred Language (Primary) | Command Line | Display             |
|-----------------|---------------------|---------------------|-----------------|
| United States | English (US) | ./menu-bar-clock.sh "EEE d MMM HH:mm" | Sun Jan 22 19:17    |
| United Kingdom | English (UK) | ./menu-bar-clock.sh "EEE d MMM HH:mm" | Sun 22 Jan 19:17    |

Here's the resulting `com.apple.menuextra.clock.plist` file:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>DateFormat</key>
	<string>EEE d MMM HH:mm</string>
	<key>FlashDateSeparators</key>
	<false/>
	<key>IsAnalog</key>
	<false/>
	<key>Show24Hour</key>
	<true/>
	<key>ShowAMPM</key>
	<false/>
	<key>ShowDate</key>
	<integer>1</integer>
	<key>ShowDayOfMonth</key>
	<true/>
	<key>ShowDayOfWeek</key>
	<true/>
	<key>ShowSeconds</key>
	<false/>
</dict>
</plist>
```

The only difference I can tell between this and the file in your final screenshot is the value of the `ShowDate` key which is `1` (show date always) as opposed to `0` (show date when space allows).

> The text of the file com.apple.menuextra.clock is gibberish, though.

It needs to be opened in an editor that can read `plist` files: BBEdit, Xcode or read from the command line using `defaults read com.apple.menuextra.clock`

> Do I need to do something to kill com.apple.controlcenter.plist?

The command is `killall ControlCenter`, which the script does for you.

Try running the script once more:  `./menu-bar-clock.sh "EEE d MMM HH:mm"`. If the result is not what you're expecting, let me know the date format displayed in the Menu Bar and the contents of the `com.apple.menuextra.clock.plist` file.

Regards, Steve.
