### ISSUE TITLE
Can show timezone?

### ISSUE THREAD

**Issue by bilogic** [tech-otaku/menu-bar-clock#12]
Is there a way to show the timezone using `z`?

**Comment by tech-otaku** [comment]
@bilogic 

Unfortunately not. As per the [README.md](https://github.com/tech-otaku/menu-bar-clock#purpose)...
> ...the script simply mimics what can otherwise be achieved by setting the format through System Settings. It is therefore limited to the formats defined by Apple.

Regards, Steve.

**Comment by bilogic** [comment]
Cool thanks, I got overly excited when I saw the formatting strings.
