### ISSUE TITLE
Not working for my desired format

### ISSUE THREAD

**Issue by AriSilveira** [tech-otaku/menu-bar-clock#13]
I followed the instructions, but I got the result below:

MacBook-Pro-de-Ari:~ ari$ cd ~/Downloads/menu-bar-clock-main
MacBook-Pro-de-Ari:menu-bar-clock-main ari$ chmod +x menu-bar-clock.sh
MacBook-Pro-de-Ari:menu-bar-clock-main ari$ ./menu-bar-clock.sh "EEE d MMM H’h’mm"

ERROR: * * * 'EEE d MMM H’h’mm' is NOT a valid Apple-supplied date and time format string for the menu bar clock * * *

MacBook-Pro-de-Ari:menu-bar-clock-main ari$

**Comment by tech-otaku** [comment]
@AriSilveira 

> ERROR: * * * 'EEE d MMM H’h’mm' is NOT a valid Apple-supplied date and time format string for the menu bar clock * * *

As per the [README](https://github.com/tech-otaku/menu-bar-clock#purpose)
> ...the script simply mimics what can otherwise be achieved by setting the format through System Settings <s>System Preferences</s>. It is therefore limited to the formats defined by Apple.

All Apple-defined formats are shown [here](https://github.com/tech-otaku/menu-bar-clock?tab=readme-ov-file#usage), where `HH` represents the hour (00-23) and `h` represents the hour (01-12). Not sure what you're hoping to display  with `H’h’`.

Regards, Steve.
