### ISSUE TITLE
Any way to remove the "at"

### ISSUE THREAD

**Issue by BoD** [tech-otaku/menu-bar-clock#2]
Using your script my clock says "Sat 28 Nov _at_ 12:06". This "at" is annoying me :) Any way to remove it?  Thanks a lot!

**Comment by tech-otaku** [comment]
It’s dependent on the Region setting in System Preferences > Language & Region > General. Having the Region set to _France_ displays the date and time with "**at**" I believe.

**Comment by BoD** [comment]
Hey thanks a lot, indeed that was it!
