### ISSUE TITLE
Add further date formats

### ISSUE THREAD

**Issue by jokuha** [tech-otaku/menu-bar-clock#3]
Hi – thank you very much for providing this tool! However, I was wondering of a more flexible approach to formatting the menubar date was possible, as it is in regional settings. I.e., I would like to set the format to something like this "EEE YYYY-MM-DD hh:mm". Any help appreciated;-)

**Comment by tech-otaku** [comment]
The script simply mimics what can be achieved setting the format through System Preferences. It is not intended to enhance the menu bar clock display beyond the limited formats defined by Apple. There are applications that allow you to customise the display of the menu bar clock, but I don't know if any will do what you're asking.
