### ISSUE TITLE
Script doesn't work on 11.3 (20E232)

### ISSUE THREAD

**Issue by RaimundasSakalauskas** [tech-otaku/menu-bar-clock#6]
HI,
Just installed Big Sur and trying to adjust the clock to my liking. By running the script at first I was able to see the new format flash for a while just to revert back to default a moment later. Any ideas what might be wrong?

**Comment by tech-otaku** [comment]
Have just tested the script with Big Sur 11.2.3 (20D91) and 11.3 (20E232) using all valid date formats and I can't reproduce the issue you're experiencing.

It's possible the preferences file may be corrupted. Have you tried deleting `~/Library/Preferences/com.apple.menuextra.clock.plist`?

**Comment by RaimundasSakalauskas** [comment]
Deleting the file seemed to help. Thank you!
