### ISSUE TITLE
Not Working on 11.4

### ISSUE THREAD

**Issue by emagaliff** [tech-otaku/menu-bar-clock#7]
The script is not working on 11.4 for all format - I ran it with the instructions and format I want, but it will not change. Specifically `"EEE d MMM HH:mm"` does not seem to be applying to the menu bar. It refreshes but the format remains the same. I also tried removing the day (`d`) and that seemed to work fine, but I cannot get the day before the month.

I tried deleting the `.plist` file as recommended in the previous issue and still no luck.

Note: Using US localization. Any way to get it to work?

**Comment by tech-otaku** [comment]
@emagaliff 

On a machine running 11.4 with _System Preferences_ > _Language & Region_ > _General_ > _Region_ set to `United States` I ran through all the valid formats and the results are as expected. The only difference from the examples in the README being the date and month were reversed: `Jul 26` as opposed to `26 Jul`.

Using the  format `"EEE d MMM HH:mm"` with the script, the menu bar displays `Mon Jul 26 15:56`.  What does yours display?

 From the command line `defaults read com.apple.menuextra.clock.plist` shows these key/value pairs...
```
    DateFormat = "EEE MMM d  H:mm";
    FlashDateSeparators = 0;
    IsAnalog = 0;
    Show24Hour = 1;
    ShowAMPM = 0;
    ShowDayOfMonth = 1;
    ShowDayOfWeek = 1;
    ShowSeconds = 0;
```

...and `defaults read .GlobalPreferences AppleICUForce12HourTime` reports...
```
The domain/default pair of (.GlobalPreferences, AppleICUForce12HourTime) does not exist
```

This is what I'd expect. What are the key/value pairs on your machine?

You also mention that  _...I cannot get the day before the month_. To be clear, by _day_ do you mean `Mon` or `26`? If it's the latter, that's due to US localisation.

Regards, Steve.

**Comment by emagaliff** [comment]
> You also mention that ...I cannot get the day before the month. To be clear, by day do you mean Mon or 26? If it's the latter, that's due to US localisation.

So the localization setting in MacOS overrides any custom formats set for the menu bar? That seems rather unintuitive (on Apple's part). I wonder if there's a way to modify the actual system localization files / settings to change the region to display the format desired.

**Comment by tech-otaku** [comment]
> So the localization setting in MacOS overrides any custom formats set for the menu bar?

Pretty much, yes. The `DateFormat` key determines what's included in the menu bar clock, but the `Region` setting in System Preferences determines how it's displayed. I use `EEE d MMM HH:mm`, but the display is different depending on the region:

| Region         | Display             |
|----------------|---------------------|
| United Kingdom | Fri 30 Jul 13:17    |
| United States  | Fri Jul 30 13:17    |
| France         | Fri 30 Jul at 13:17 |
| Germany        | Fri 30. Jul 13:17   |
| Czechia        | Fri 30. 7. 13:17     |

There are applications that allow the menu bar clock to be customised, but never having used them I can't vouch for their effectiveness. 

Regards, Steve.

**Comment by kgorskii** [comment]
Hi @tech-otaku - I tried 
`./menu-bar-clock.sh "EEE d MMM HH:mm"`
but the way date and time looks in menu bar didn't change - I still see the format of "Fri. 30.01 o  13:17". I wanted to remove this "o" and additional space after it before time.
My region is set to Poland.
Thanks

**Comment by tech-otaku** [comment]
@kgorski

In this instance there seems to be another setting affecting the date/time display - the primary preferred language set in _System Preferences_ > _Language & Region_ > _General_ > _Preferred languages:_

 If you're running macOS Monterey (12.1)  and using a format of `EEE d MMM HH:mm`:

| Region         | Preferred Language (Primary) | Display             |
|-----------------|---------------------|---------------------|
| United Kingdom | English | Sat 22 Jan 13:49    |
| United Kingdom | Polski | Sob. 22.01 o  13:49    |
| Poland  | English | Sat 22 Jan 13:49    |
| Poland  | Polski | Sob. 22.01 o  13:49    |

But for macOS Big Sur (11.6.1) the same format gives (no "o"):

| Region         | Preferred Language (Primary) | Display             |
|-----------------|---------------------|---------------------|
| United Kingdom | English | Sat 22 Jan 13:49    |
| United Kingdom | Polski | Sob. 22.01 13:49    |
| Poland  | English | Sat 22 Jan 13:49    |
| Poland  | Polski | Sob. 22.01 13:49    |

These are Apple-supplied formats and unfortunately not something the script has any control over.

Regards, Steve.
