### ISSUE TITLE
macOS Monterey 12.1 issue

### ISSUE THREAD

**Issue by kgorskii** [tech-otaku/menu-bar-clock#8]
Hi @tech-otaku - I tried
./menu-bar-clock.sh "EEE d MMM HH:mm
but the way date and time looks in menu bar didn't change - I still see the format of "Fri. 30.01 o 13:17". I wanted to remove this "o" and additional space after it before the time part.
My region is set to Poland. File com.apple.menuextra.clock.plist shows as follows:
`
<key>DateFormat</key>  
<string>EEE d MMM HH:mm</string>
<key>FlashDateSeparators</key>
<false/>
<key>IsAnalog</key>
<false/>
<key>Show24Hour</key>
<true/>
<key>ShowAMPM</key>
<false/>
<key>ShowDayOfMonth</key>
<true/>
<key>ShowDayOfWeek</key>
<true/>
<key>ShowSeconds</key>
<false/>
`
Thanks

**Comment by tech-otaku** [comment]
@kgorski

In this instance there seems to be another setting affecting the date/time display - the primary preferred language set in _System Preferences_ > _Language & Region_ > _General_ > _Preferred languages:_

Running macOS Monterey (12.1)  and using a format of `EEE d MMM HH:mm`:

| Region         | Preferred Language (Primary) | Display             |
|-----------------|---------------------|---------------------|
| United Kingdom | English | Sat 22 Jan 13:49    |
| United Kingdom | Polski | Sob. 22.01 o  13:49    |
| Poland  | English | Sat 22 Jan 13:49    |
| Poland  | Polski | Sob. 22.01 o  13:49    |

But for macOS Big Sur (11.6.1) the same format gives (no "o"):

| Region         | Preferred Language (Primary) | Display             |
|-----------------|---------------------|---------------------|
| United Kingdom | English | Sat 22 Jan 13:49    |
| United Kingdom | Polski | Sob. 22.01 13:49    |
| Poland  | English | Sat 22 Jan 13:49    |
| Poland  | Polski | Sob. 22.01 13:49    |

These are Apple-supplied formats and unfortunately not something the script has any control over.

Regards, Steve.
